<template>
  <DashboardLayout>
    <template #breadcrumb>
      <span>Ops</span> <span class="breadcrumb-sep">/</span> <span>Reports</span>
    </template>
    
    <div class="page-header">
      <h1 class="page-title">Operations Reports</h1>
      <div class="page-actions">
        <button class="btn btn-primary">
          <span>📊</span> Generate Report
        </button>
      </div>
    </div>
    
    <div class="grid grid-2">
      <Card title="Report Templates">
        <div class="templates-list">
          <div v-for="i in 6" :key="i" class="template-item">
            <div class="template-icon">📊</div>
            <div class="template-info">
              <div class="template-name">Report Template {{ i }}</div>
              <div class="template-description">Description for report template {{ i }}</div>
            </div>
            <button class="btn btn-outline btn-sm">Generate</button>
          </div>
        </div>
      </Card>
      
      <Card title="Report Filters">
        <form @submit.prevent="generateReport">
          <div class="form-group">
            <label class="form-label">Report Type</label>
            <select class="form-select" v-model="reportForm.type">
              <option value="">Select a report type</option>
              <option value="bookings">Bookings Summary</option>
              <option value="revenue">Revenue Analysis</option>
              <option value="users">User Activity</option>
              <option value="services">Service Performance</option>
            </select>
          </div>
          
          <div class="form-group">
            <label class="form-label">Date Range</label>
            <div class="date-range">
              <input type="date" class="form-input" v-model="reportForm.startDate">
              <span>to</span>
              <input type="date" class="form-input" v-model="reportForm.endDate">
            </div>
          </div>
          
          <div class="form-group">
            <label class="form-label">Format</label>
            <div class="format-options">
              <label class="format-option">
                <input type="radio" v-model="reportForm.format" value="pdf">
                <span class="format-label">PDF</span>
              </label>
              <label class="format-option">
                <input type="radio" v-model="reportForm.format" value="csv">
                <span class="format-label">CSV</span>
              </label>
              <label class="format-option">
                <input type="radio" v-model="reportForm.format" value="xlsx">
                <span class="format-label">Excel</span>
              </label>
            </div>
          </div>
          
          <div class="form-group">
            <label class="form-label">Additional Options</label>
            <div class="options-list">
              <label class="option-item">
                <input type="checkbox" v-model="reportForm.includeCharts">
                <span>Include charts</span>
              </label>
              <label class="option-item">
                <input type="checkbox" v-model="reportForm.includeSummary">
                <span>Include summary</span>
              </label>
              <label class="option-item">
                <input type="checkbox" v-model="reportForm.sendEmail">
                <span>Send via email</span>
              </label>
            </div>
          </div>
          
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">Generate Report</button>
          </div>
        </form>
      </Card>
    </div>
    
    <Card title="Recent Reports">
      <Table :headers="['Report Name', 'Generated By', 'Date', 'Status', 'Actions']">
        <tr v-for="i in 8" :key="i">
          <td>
            <div class="report-name">Monthly Report {{ i }}</div>
            <div class="report-type">Bookings Summary</div>
          </td>
          <td>
            <div class="table-user">
              <div class="user-avatar">{{ getRandomInitial() }}</div>
              <div class="user-details">
                <div class="user-name">User {{ i }}</div>
              </div>
            </div>
          </td>
          <td>{{ formatDate(subDays(new Date(), i * 2)) }}</td>
          <td>
            <Badge v-if="i % 3 === 0" type="success">Completed</Badge>
            <Badge v-else-if="i % 3 === 1" type="warning">Processing</Badge>
            <Badge v-else type="error">Failed</Badge>
          </td>
          <td>
            <div class="table-actions">
              <button class="btn-icon" title="View">👁️</button>
              <button class="btn-icon" title="Download">⬇️</button>
              <button class="btn-icon" title="Delete">🗑️</button>
            </div>
          </td>
        </tr>
      </Table>
      
      <template #footer>
        <div class="pagination">
          <button class="btn btn-outline">Previous</button>
          <span class="pagination-info">Page 1 of 5</span>
          <button class="btn btn-outline">Next</button>
        </div>
      </template>
    </Card>
  </DashboardLayout>
</template>

<script setup>
import { reactive } from 'vue'
import DashboardLayout from '@/Layouts/Dashboard/DashboardLayout.vue'
import Card from '@/Components/UI/Card.vue'
import Table from '@/Components/UI/Table.vue'
import Badge from '@/Components/UI/Badge.vue'

// Form data
const reportForm = reactive({
  type: '',
  startDate: '',
  endDate: '',
  format: 'pdf',
  includeCharts: true,
  includeSummary: true,
  sendEmail: false
})

// Helper functions
function getRandomInitial() {
  const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  return letters.charAt(Math.floor(Math.random() * letters.length))
}

function formatDate(date) {
  return date.toLocaleDateString('en-US', { 
    month: 'short', 
    day: 'numeric', 
    year: 'numeric' 
  })
}

function subDays(date, days) {
  const result = new Date(date)
  result.setDate(result.getDate() - days)
  return result
}

// Form submission handler
function generateReport() {
  console.log('Generating report:', reportForm)
  alert('Report generation started. You will be notified when it\'s ready.')
}
</script>

<style scoped>
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 600;
  color: #1e293b;
  margin: 0;
}

.page-actions {
  display: flex;
  gap: 0.5rem;
}

.grid {
  display: grid;
  gap: 1.5rem;
  margin-bottom: 1.5rem;
}

.grid-2 {
  grid-template-columns: 1fr 1fr;
}

.form-group {
  margin-bottom: 1rem;
}

.form-label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: #1e293b;
}

.form-select {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #cbd5e1;
  border-radius: 0.375rem;
  font-size: 0.875rem;
  transition: all 0.2s ease;
}

.form-select:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.form-input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #cbd5e1;
  border-radius: 0.375rem;
  font-size: 0.875rem;
  transition: all 0.2s ease;
}

.form-input:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.date-range {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.format-options {
  display: flex;
  gap: 1rem;
}

.format-option {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.format-label {
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
  background-color: #f1f5f9;
  font-size: 0.875rem;
  cursor: pointer;
}

.options-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.option-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.form-actions {
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid #e2e8f0;
}

.templates-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.template-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  border: 1px solid #e2e8f0;
  border-radius: 0.375rem;
  background-color: #f8fafc;
}

.template-icon {
  font-size: 1.5rem;
}

.template-info {
  flex: 1;
}

.template-name {
  font-weight: 600;
  color: #1e293b;
  margin-bottom: 0.25rem;
}

.template-description {
  font-size: 0.875rem;
  color: #64748b;
}

.table-user {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.user-avatar {
  width: 2rem;
  height: 2rem;
  border-radius: 9999px;
  background-color: #3b82f6;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-weight: 600;
  font-size: 0.75rem;
}

.user-details {
  min-width: 0;
}

.user-name {
  font-weight: 500;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.report-name {
  font-weight: 600;
  color: #1e293b;
  margin-bottom: 0.25rem;
}

.report-type {
  font-size: 0.875rem;
  color: #64748b;
}

.table-actions {
  display: flex;
  gap: 0.5rem;
}

.btn-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 2rem;
  height: 2rem;
  border-radius: 0.375rem;
  background-color: #f1f5f9;
  color: #64748b;
  text-decoration: none;
  font-size: 0.875rem;
  border: none;
  cursor: pointer;
}

.btn-icon:hover {
  background-color: #e2e8f0;
}

.pagination {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem 0;
}

.pagination-info {
  color: #64748b;
  font-size: 0.875rem;
}

@media (max-width: 768px) {
  .grid-2 {
    grid-template-columns: 1fr;
  }
  
  .date-range {
    flex-direction: column;
    align-items: stretch;
  }
  
  .format-options {
    flex-direction: column;
    gap: 0.5rem;
  }
}
</style>